spring:
  application:
    name: NexBlog-Backend

  # 1. H2 数据库配置
  datasource:
    # 使用文件模式存储数据库，这就不会重启丢失了
    # ./data/NexBlog 表示会在项目运行目录下创建一个 data 文件夹存放数据库文件
    url: jdbc:h2:file:./data/NexBlog
    driverClassName: org.h2.Driver
    username: pengkk27
    password: 123456

  # 开启 H2 的网页版控制台
  h2:
    console:
      enabled: true
      # 你可以在浏览器通过这个路径访问数据库
      path: /h2-console

  # 2. JPA 配置
  jpa:
    # 自动生成数据库表！(update 表示如果实体类变了，表结构跟着变)
    hibernate:
      ddl-auto: update
    # 在控制台打印出 JPA 帮你写的 SQL 语句，方便学习
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  # ai 配置
  ai:
    ollama:
    # 你的本地 Ollama 默认运行端口就是 11434
      base-url: http://localhost:11434
      chat:
          # 这里填你在电脑上用 Ollama 拉取的模型名字！
          # 比如你拉取了千问：qwen2.5:7b，或者 llama3 等
          model: qwen2.5:7b

nexblog:
  auth:
    token-secret: ${NEXBLOG_AUTH_TOKEN_SECRET:nexblog-dev-token-secret-please-change-in-prod}
    token-ttl-minutes: ${NEXBLOG_AUTH_TOKEN_TTL_MINUTES:720}
